# Generated by Django 3.0.1 on 2020-02-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DanceClub', '0004_admin_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='types',
        ),
    ]
