# Generated by Django 3.0.1 on 2020-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanceClub', '0005_remove_user_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='classes',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='admin',
            name='gender',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
