# Generated by Django 3.0.1 on 2020-02-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanceClub', '0006_auto_20200210_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('class_description', models.CharField(max_length=100)),
                ('class_date', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(max_length=50),
        ),
    ]
