# Generated by Django 3.0.1 on 2020-02-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanceClub', '0007_auto_20200210_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
