# Generated by Django 3.0.1 on 2020-02-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DanceClub', '0008_auto_20200210_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('booking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('class_description', models.CharField(max_length=100)),
                ('class_types', models.CharField(max_length=100)),
                ('class_shift', models.CharField(max_length=100)),
                ('booking_date', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DanceClub.User')),
            ],
            options={
                'db_table': 'bookclass',
            },
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
