# Generated by Django 3.0.1 on 2020-02-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DanceClub', '0009_auto_20200210_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='class_name',
            new_name='student_name',
        ),
    ]
