# Generated by Django 3.0.1 on 2020-02-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DanceClub', '0010_auto_20200211_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='class_description',
        ),
    ]
