# Generated by Django 3.0.1 on 2020-02-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanceClub', '0011_remove_book_class_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=100)),
                ('admin_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='user_id',
        ),
    ]
