# Generated by Django 3.0.1 on 2020-02-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanceClub', '0013_event_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('class_types', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sets',
            },
        ),
    ]
