# Generated by Django 3.0.1 on 2020-02-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanceClub', '0014_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='class_shift',
            field=models.CharField(default='', max_length=100),
        ),
    ]
